-- Default (global) categories, available to every user via categories_select policy
insert into categories (user_id, name, type, icon, color, is_default) values
  (null, 'Makanan & Minuman', 'expense', 'utensils', '#F59E0B', true),
  (null, 'Transportasi', 'expense', 'car', '#60A5FA', true),
  (null, 'Belanja', 'expense', 'shopping-bag', '#EF4444', true),
  (null, 'Tagihan', 'expense', 'receipt', '#0F172A', true),
  (null, 'Hiburan', 'expense', 'clapperboard', '#8B5CF6', true),
  (null, 'Kesehatan', 'expense', 'heart-pulse', '#EC4899', true),
  (null, 'Pendidikan', 'expense', 'graduation-cap', '#2563EB', true),
  (null, 'Keluarga', 'expense', 'users', '#10B981', true),
  (null, 'Travel', 'expense', 'plane', '#06B6D4', true),
  (null, 'Langganan', 'expense', 'repeat', '#F97316', true),
  (null, 'Internet', 'expense', 'wifi', '#3B82F6', true),
  (null, 'Listrik', 'expense', 'zap', '#EAB308', true),
  (null, 'Sewa', 'expense', 'home', '#64748B', true),
  (null, 'Investasi', 'expense', 'trending-up', '#10B981', true),
  (null, 'Lainnya', 'expense', 'ellipsis', '#94A3B8', true),
  (null, 'Gaji', 'income', 'wallet', '#10B981', true),
  (null, 'Freelance', 'income', 'laptop', '#2563EB', true),
  (null, 'Bonus', 'income', 'gift', '#F59E0B', true),
  (null, 'Bisnis', 'income', 'briefcase', '#8B5CF6', true),
  (null, 'Investasi', 'income', 'trending-up', '#10B981', true),
  (null, 'Hadiah', 'income', 'gift', '#EC4899', true),
  (null, 'Lainnya', 'income', 'ellipsis', '#94A3B8', true);
